=== aleksandriliev8/XML_project/XML_Schema/bus_station.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="FrequencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hourly"/>
            <xs:enumeration value="Daily"/>
            <xs:enumeration value="Weekly"/>
            <xs:enumeration value="Monthly"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="StopType">
        <xs:sequence>
            <xs:element name="StopDetails" type="xs:string" />
            <xs:element name="EstimatedTime" type="xs:time" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ServiceType">
        <xs:sequence>
            <xs:element name="ServiceHours" type="xs:string"/>
            <xs:element name="ServiceProvider" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="description" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="RouteType">
        <xs:sequence>
            <xs:element name="Stops">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Stop" type="StopType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="RouteManager" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="destination" type="xs:string" use="required"/>
        <xs:attribute name="frequency" type="FrequencyType" use="required"/>
    </xs:complexType>

    <xs:complexType name="ServicesType">
        <xs:sequence>
            <xs:element name="service" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="BusStations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="BusStation" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="location" type="xs:string" />
                            <xs:element name="capacity" type="xs:positiveInteger" />
                            <xs:element name="manager" type="xs:string" />
                            <xs:element name="contactInfo" type="xs:string" />
                            <xs:element name="openingHours" type="xs:string" />
                            <xs:element name="services" type="ServicesType"/>
                            <xs:element name="Routes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Route" type="RouteType" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aleksandriliev8/XML_project/XML_Schema/bus_station.xml
<?xml version="1.0" encoding="UTF-8"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bus_station.xsd">
    <BusStation>
        <name>Централна Автогара София</name>
        <location>София, България</location>
        <capacity>50</capacity>
        <manager>Иван Петров</manager>
        <contactInfo>+359123456789</contactInfo>
        <openingHours>06:00 - 22:00</openingHours>

        <services>
            <service>Кафене</service>
            <service>Тоалетна</service>
        </services>

        <Routes>
            <Route id="R001" destination="Пловдив" frequency="Hourly">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>20:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Пазарджик" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>21:30:00</EstimatedTime>
                    </Stop>
                    <Stop name="Пловдив Юг" type="автогара">
                        <StopDetails>Крайна точка на маршрута</StopDetails>
                        <EstimatedTime>22:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Георги Иванов</RouteManager>
            </Route>
            <Route id="R002" destination="Варна" frequency="Daily">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Велико Търново" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>13:30:00</EstimatedTime>
                    </Stop>
                    <Stop name="Варна Централна" type="автогара">
                        <StopDetails>Крайна точка</StopDetails>
                        <EstimatedTime>16:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Стефан Петров</RouteManager>
            </Route>
        </Routes>
    </BusStation>
</BusStations>

=== aleksandriliev8/XML_project/XSLT/Transformations/html_transformations/ruse_bus_station.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../XSLT/HTML/working_hours_contacts_to_html.xslt"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../XML_Schema/bus_station.xsd">
    <BusStation>
        <name>Автогара Русе</name>
        <location>Русе, България</location>
        <capacity>20</capacity>
        <manager>Ангел Иванов</manager>
        <contactInfo>+359112244556</contactInfo>
        <openingHours>07:00 - 20:00</openingHours>
        <services>
            <service>Магазин</service>
        </services>
        <Routes>
            <Route id="R005" destination="Силистра" frequency="Daily">
                <Stops>
                    <Stop name="Русе Централна" type="автогара">
                        <StopDetails>Начална точка</StopDetails>
                        <EstimatedTime>08:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Тутракан" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>09:30:00</EstimatedTime>
                    </Stop>
                    <Stop name="Силистра Централна" type="автогара">
                        <StopDetails>Крайна точка</StopDetails>
                        <EstimatedTime>10:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Михаил Георгиев</RouteManager>
            </Route>
        </Routes>
    </BusStation>
</BusStations>

=== aleksandriliev8/XML_project/XSLT/Transformations/text_transformations/sofia_bus_station.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../XSLT/TEXT/routes_description_to_text.xslt"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../XML_Schema/bus_station.xsd">
    <BusStation>
        <name>Централна Автогара София</name>
        <location>София, България</location>
        <capacity>50</capacity>
        <manager>Иван Петров</manager>
        <contactInfo>+359123456789, info@centralbus.bg</contactInfo>
        <openingHours>06:00 - 22:00</openingHours>
        <services>
            <service>Билетен център</service>
            <service>Кафе-ресторант</service>
            <service>Чакалня</service>
            <service>Безжичен интернет</service>
        </services>
        <Routes>
            <Route id="R001" destination="Пловдив" frequency="Hourly">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>08:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Тракия Пловдив" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Георги Иванов</RouteManager>
            </Route>
            <Route id="R002" destination="Варна" frequency="Hourly">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>09:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Шумен Централна" type="автогара">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>13:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Варна Централна" type="автогара">
                        <StopDetails>Крайна точка на маршрута</StopDetails>
                        <EstimatedTime>15:00:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Мария Стоянова</RouteManager>
            </Route>
        </Routes>
    </BusStation>

    <BusStation>
        <name>Автогара Пловдив</name>
        <location>Пловдив, България</location>
        <capacity>30</capacity>
        <manager>Антон Димитров</manager>
        <contactInfo>+359987654321, contact@plovdivbus.bg</contactInfo>
        <openingHours>07:00 - 21:00</openingHours>
        <services>
            <service>Банкомат</service>
            <service>Информационен център</service>
        </services>
        <Routes>
            <Route id="R003" destination="Стара Загора" frequency="Daily">
                <Stops>
                    <Stop name="Пловдив Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Стара Загора Централна" type="автогара">
                        <StopDetails>Крайна точка на маршрута</StopDetails>
                        <EstimatedTime>12:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Светослав Николов</RouteManager>
            </Route>
        </Routes>
    </BusStation>
</BusStations>

=== aleksandriliev8/XML_project/XSLT/Transformations/xml_transformations/varna_bus_station.xml
<?xml version="1.0" encoding="UTF-8"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XML_Schema/bus_station.xsd">
    <BusStation>
        <name>Автогара Варна</name>
        <location>Варна, България</location>
        <capacity>40</capacity>
        <manager>Стефан Костов</manager>
        <contactInfo>+359987654321</contactInfo>
        <openingHours>05:00 - 23:00</openingHours>
        <services>
            <service>Снек бар</service>
        </services>

        <Routes>
            <Route id="R003" destination="Бургас" frequency="Daily">
                <Stops>
                    <Stop name="Варна Централна" type="автогара">
                        <StopDetails>Начална точка</StopDetails>
                        <EstimatedTime>07:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Обзор" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>08:30:00</EstimatedTime>
                    </Stop>
                    <Stop name="Бургас Юг" type="автогара">
                        <StopDetails>Крайна точка</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Ивайло Димитров</RouteManager>
            </Route>
        </Routes>
    </BusStation>
</BusStations>

=== aleksandriliev8/XML_project/Second_component/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bus_station.xsd">
    <BusStation>
        <name>Централна Автогара София</name>
        <location>София, България</location>
        <capacity>50</capacity>
        <manager>Иван Петров</manager>
        <contactInfo>
            <phone>+359123456789</phone>
            <email>info@centralbus.bg</email>
        </contactInfo>
        <openingHours>06:00 - 22:00</openingHours>
        <services>
            <service>Билетен център</service>
            <service>Кафе-ресторант</service>
            <service>Чакалня</service>
            <service>Безжичен интернет</service>
        </services>
        <Routes>
            <Route id="R001" destination="Пловдив" frequency="Hourly">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>08:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Тракия Пловдив" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Георги Иванов</RouteManager>
            </Route>
            <Route id="R002" destination="Варна" frequency="Every 2 Hours">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>09:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Шумен Централна" type="автогара">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>13:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Варна Централна" type="автогара">
                        <StopDetails>Крайна точка на маршрута</StopDetails>
                        <EstimatedTime>15:00:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Мария Стоянова</RouteManager>
            </Route>
        </Routes>
    </BusStation>

    <BusStation>
        <name>Автогара Пловдив</name>
        <location>Пловдив, България</location>
        <capacity>30</capacity>
        <manager>Антон Димитров</manager>
        <contactInfo>
            <phone>+359987654321</phone>
            <email>contact@plovdivbus.bg</email>
        </contactInfo>
        <openingHours>07:00 - 21:00</openingHours>
        <services>
            <service>Банкомат</service>
            <service>Информационен център</service>
        </services>
        <Routes>
            <Route id="R003" destination="Стара Загора" frequency="Every 3 Hours">
                <Stops>
                    <Stop name="Пловдив Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Стара Загора Централна" type="автогара">
                        <StopDetails>Крайна точка на маршрута</StopDetails>
                        <EstimatedTime>12:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Светослав Николов</RouteManager>
            </Route>
        </Routes>
    </BusStation>
</BusStations>

=== aleksandriliev8/XML_project/XSLT/Transformations/html_transformations/plovdiv_bus_station.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../XSLT/HTML/routes_info_to_html.xslt"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../XML_Schema/bus_station.xsd">
    <BusStation>
        <name>Автогара Пловдив</name>
        <location>Пловдив, България</location>
        <capacity>35</capacity>
        <manager>Мария Колева</manager>
        <contactInfo>+359112233445</contactInfo>
        <openingHours>06:30 - 21:00</openingHours>
        <services>
            <service>Информация</service>
        </services>

        <Routes>
            <Route id="R004" destination="Стара Загора" frequency="Hourly">
                <Stops>
                    <Stop name="Пловдив Юг" type="автогара">
                        <StopDetails>Начална спирка</StopDetails>
                        <EstimatedTime>08:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Чирпан" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>09:15:00</EstimatedTime>
                    </Stop>
                    <Stop name="Стара Загора Централна" type="автогара">
                        <StopDetails>Крайна точка</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Емил Петров</RouteManager>
            </Route>
        </Routes>
    </BusStation>
</BusStations>

=== aleksandriliev8/XML_project/DOM/examples/5.xml
<?xml version="1.0" encoding="UTF-8"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XML_Schema/bus_station.xsd">
    <BusStation>
        <name>Автогара Благоевград</name>
        <location>Благоевград, България</location>
        <capacity>25</capacity>
        <manager>Калоян Димитров</manager>
        <contactInfo>+359123321456</contactInfo>
        <openingHours>05:30 - 22:30</openingHours>
        <services>
            <service>Билетен център</service>
        </services>
        <Routes>
            <Route id="R006" destination="Сандански" frequency="Hourly">
                <Stops>
                    <Stop name="Благоевград Централна" type="автогара">
                        <StopDetails>Начална точка</StopDetails>
                        <EstimatedTime>06:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Кресна" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>06:45:00</EstimatedTime>
                    </Stop>
                    <Stop name="Сандански Централна" type="автогара">
                        <StopDetails>Крайна точка</StopDetails>
                        <EstimatedTime>07:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Виктор Маринов</RouteManager>
            </Route>
        </Routes>
    </BusStation>
</BusStations>

=== aleksandriliev8/XML_project/First_component/bus_station.xml
<?xml version="1.0" encoding="UTF-8"?>
<BusStations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bus_station.xsd">
    <BusStation>
        <name>Централна Автогара София</name>
        <location>София, България</location>
        <capacity>50</capacity>
        <manager>Иван Петров</manager>
        <contactInfo>+359123456789</contactInfo>
        <openingHours>06:00 - 22:00</openingHours>
        <Routes>
            <Route id="R001" destination="Пловдив" frequency="Hourly">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>20:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Пазарджик" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>21:30:00</EstimatedTime>
                    </Stop>
                    <Stop name="Пловдив Юг" type="автогара">
                        <StopDetails>Крайна точка на маршрута</StopDetails>
                        <EstimatedTime>22:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Георги Иванов</RouteManager>
            </Route>
            <Route id="R002" destination="Варна" frequency="Daily">
                <Stops>
                    <Stop name="София Централна" type="автогара">
                        <StopDetails>Начална точка на маршрута</StopDetails>
                        <EstimatedTime>10:00:00</EstimatedTime>
                    </Stop>
                    <Stop name="Велико Търново" type="спирка">
                        <StopDetails>Междинна спирка</StopDetails>
                        <EstimatedTime>13:30:00</EstimatedTime>
                    </Stop>
                    <Stop name="Варна Централна" type="автогара">
                        <StopDetails>Крайна точка</StopDetails>
                        <EstimatedTime>16:30:00</EstimatedTime>
                    </Stop>
                </Stops>
                <RouteManager>Стефан Петров</RouteManager>
            </Route>
        </Routes>
        <Services>
            <Service name="Кафене" description="Топли напитки и закуски">
                <ServiceHours>06:00 - 22:00</ServiceHours>
                <ServiceProvider>Кафе Експрес</ServiceProvider>
            </Service>
            <Service name="Тоалетна" description="Безплатно за пътници">
                <ServiceHours>06:00 - 22:00</ServiceHours>
                <ServiceProvider>Мистър Пропър ООД</ServiceProvider>
            </Service>
        </Services>
        <Amenities>
            <Restrooms>true</Restrooms>
            <Parking>true</Parking>
            <Shops>true</Shops>
        </Amenities>
        <NearbyAttractions>"Национален дворец на културата", Църква "Света Неделя"</NearbyAttractions>
    </BusStation>
</BusStations>
